version: '3.4'

services:
  smartcodeql:
    image: smartcodeql
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
      - initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
