version: '3.4'

services:
  smartcodeql:
    image: smartcodeql
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 40000:40000
    depends_on:
      - codeql-container
      - postgres
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  codeql-container:
    image: mcr.microsoft.com/cstsectools/codeql-container
    volumes: 
      - /home/weiyi/code/guava/guava:/opt/src
      - ./results:/opt/results
    environment:
      CODEQL_CLI_ARGS: version
volumes:
  db_data:
    driver: local



